### ISSUE TITLE
Button-Icons disappear after restarting Visual Studio

### ISSUE THREAD

**Issue by ytuploader** [madskristensen/MyCompany#1]
First of all, this is a really nice idea and project.
It made me spend hours getting into Visual Studio Extensions while adding buttons, icons and even sub-menus. I had alot of fun.

But unfortunately there is a problem.
When i install my built .vsix all icons disappear. Yet the buttons are still completly working fine. 

More precise:
While debugging this problem never occures. I can start the debugged version as many times as i want, the icons are always there. 
When i install the built version and start it for the first time everything is fine as well. But after a restart of Visual Studio, all icons are gone. When i deactivate and then re-activate the Extension this is also the case: In the first run all icons are there, in any run after the first one all icons are gone. I also did optimize my icons with your IconOptimizer extension. And i also deactivated every other extension i had installed but this did not fix the problem. The last thing i tried was downloading and installing the fresh MyCompany Extension from here and the same problem did also occure. But not as hard as with my edited version of the extension. Only sometimes the fruit-icon of the "Developer Wiki" disappeared. The other gray icons of "Build Server" and "HR Portal" never disappeared. So i guess the problem has something to do with our custom added monikers.imagemanifest? And the problem occures way more often for my edited version because i have 8x3 icons added?

**Comment by madskristensen** [comment]
Good catch. I forgot to add the [ProvideBindingPath] attribute as shown here: https://github.com/madskristensen/MyCompany/blob/master/src/MyCompanyPackage.cs#L12

Just add that attribute to your package class and it should work
